name: Build and Deploy Storybook
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        
      - name: Setup Node and Cache 🔧
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: yarn
      - name: Install Dependencies 📦
        run: yarn install --frozen-lockfile
      - name: Build Storybook 🔨
        run: yarn build-storybook
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs
          folder: docs-build
          clean: true
          target-folder: /