---
name: 📖 Build and Deploy Storybook
permissions:
  contents: write
on:
  push:
    branches: [main]
jobs:
  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout Repository
        uses: actions/checkout@v6
      - name: 🔧 Setup Node and Cache
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: 📦 Install Dependencies
        run: yarn install --immutable
      - name: 🔨 Build Storybook
        run: yarn build-storybook
      - name: 🚀 Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: storybook-static
          clean: true
